### ISSUE TITLE
Visual Studio Code Support

### ISSUE THREAD

**Issue by raywan** [arcticicestudio/nord#13]
Hello! 

This is my absolute favourite theme and i'm currently using it for **everything** - Vim, Terminal, and Atom. I just switched from Atom to VSCode and if it's not too much trouble, I would love support for it. 

Thank you so much for your hard work!  💯

**Comment by arcticicestudio** [comment]
Hello raywan!
Nice to see you like it 😄 

I've added support for Visual Studio Code to my TODO lists, but haven't got the time to start working on it.
I've done a small research and they're using the TextMate theme format which is used by some other apps too.
This means I can create multiple port projects with this theme file.

Unfortunately the [theme API only allows to create syntax themes](https://code.visualstudio.com/docs/extensions/our-approach#_extensibility-api).
It is possible to create a UI theme using third-party extensions, but these are only hacky workarounds which may break with every official update or may make the whole app unstable and should be avoided.
Anyway, it looks like [there are plans to support UI themes](https://github.com/Microsoft/vscode/issues/1833) which [has been officially announced by a VSCode team member](https://github.com/Microsoft/vscode/issues/1833#issuecomment-270738260) last month referencing to [this roadmap](https://github.com/Microsoft/vscode/issues/17608).

I'll start working on this- and the #6 Emacs port project as soon as I've got some freetime 😃

**Comment by jorgegonzalez** [comment]
Just voicing my desire for this as well. Nord is awesome and VSCode support would be very much appreciated.

**Comment by akellermann97** [comment]
Yeah this theme has got to be my favorite theme in a long time, really looking forward to this port!

**Comment by arcticicestudio** [comment]
❄️  Initial version :label: [0.1.0](https://github.com/arcticicestudio/nord-visual-studio-code/releases/tag/v0.1.0) has been released to the [GitHub repository](https://github.com/arcticicestudio/nord-visual-studio-code) and published to the [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=arcticicestudio.nord-visual-studio-code)!

**Comment by nomenon** [comment]
![default](https://cloud.githubusercontent.com/assets/16668962/24259699/4ee6e006-0ffa-11e7-899c-660e4f3489a0.png)

**Comment by arcticicestudio** [comment]
> It is possible to create a UI theme using third-party extensions, but these are only hacky workarounds which may break with every official update or may make the whole app unstable and should be avoided.

Anyway, it seems like the UI API is about to arrive soon as I've posted in [arcticicestudio/nord-visual-studio-code #5](https://github.com/arcticicestudio/nord-visual-studio-code/issues/5#issuecomment-285929808) some days ago.

**Comment by SteveALee** [comment]
I've installed Nord from the market place and using the latest April release of code but still no full workspace theming. The built in themes have been updated and I read a note somewhere saying it was implemented for Nord.

Could you clarify the status?

thanks

**Comment by arcticicestudio** [comment]
The PR [arcticicestudio/nord-visual-studio-code #11](https://github.com/arcticicestudio/nord-visual-studio-code/pull/11) is currently work in progress. I'll try to implement the suggested improvements some user posted and fix the remaining issues. Maybe it gets merged today so I can ship it with the next extension release version.

**Comment by arcticicestudio** [comment]
@SteveALee  The new workbench UI is now available as of the 🚢 shipped extension package release version 🏷 [0.2.0](https://github.com/arcticicestudio/nord-visual-studio-code/releases/tag/v0.2.0).
