### ISSUE TITLE
Wayland title bars

### ISSUE THREAD

**Issue by Nick-Winkley** [arcticicestudio/nord#135]
Possible bug?

When using Wayland on Manjaro KDE 20.0.1, the title bars appear as a grainy black, with no buttons or text. Switching to another theme fixes this, but is there a workaround or solution for Nord?

**Comment by arcticicestudio** [comment]
Hi @nicolaswinkley, there is currently some context missing about this topic. There is currently no official port project or explicit support for any _Wayland_ or KDE components. It might be possible that you're using a port made by another Nord user. Please open an new issue in the corresponding repository.
