### ISSUE TITLE
Port for `nnn`

### ISSUE THREAD

**Issue by duganchen** [arcticicestudio/nord#142]
Just wanted to contribute my attempt at an nnn theme.

I've tested it under the following. The testing process was to compare it to ls listings made using nord-dircolors:

* Kitty in Fedora 32 with a Nord Kitty colorscheme and Nord Xresources
* iterm2 on OSX with a Nord colorscheme

```
# shellcheck shell=sh

# Tested in iterm using the script here:
# https://askubuntu.com/a/821163

BLK="0B"
CHR="0B"
DIR="04"
EXEC="06"
FILE="00"
MULTIHARDLINK="06"
LINK="06"
MISSING=00 # Not sure what this is
ORPHAN="09"
FIFO="06"
SOCK="0B"
OTHER=06

export NNN_FCOLORS="$BLK$CHR$DIR$EXEC$FILE$MULTIHARDLINK$LINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"
```

**Comment by arcticicestudio** [comment]
Hi @duganchen :wave:, thanks for your contribution :+1:

I've added it to the [backlog][bli] and @-mention you as soon as I start working on it so you can track the progress or contribute ideas for this port project.

Please note that it may take some time for this port project to be implemented.
There is a massive amount of other issues & PRs over many other port projects with requests and proposals waiting in the queue as well as [50+ port project requests in the backlog][bli]. I'm currently very busy working and focusing on the [data transition of all port projects][dt] to the [new and shiny website and documentations][h] to finally have a „single source of truth“ for Nord and all related data, [reduce the maintenance overhead and increase the overall project quality][lp]. :octocat:

Please also take into account that I work as a software developer in the "real world" and I hope you understand that the time to work on my projects may vary depending on my free time. :pray:

The code you've posted here can already be useful for other users who can use it in the meantime until an official port is available. This could also help to bootstrap the official port later on by using it as fundamental code base :smile:

[bli]: https://github.com/arcticicestudio/nord/projects/1#column-288113
[dt]: https://github.com/arcticicestudio/nord-docs/issues/133
[h]: https://www.nordtheme.com
[lp]: https://github.com/arcticicestudio/nord-docs/issues/1

**Comment by ghost** [comment]
> Just wanted to contribute my attempt at an nnn theme.
> 
> I've tested it under the following. The testing process was to compare it to ls listings made using nord-dircolors:
> 
>     * Kitty in Fedora 32 with a Nord Kitty colorscheme and Nord Xresources
> 
>     * iterm2 on OSX with a Nord colorscheme
> 
> 
> ```
> # shellcheck shell=sh
> 
> # Tested in iterm using the script here:
> # https://askubuntu.com/a/821163
> 
> BLK="0B"
> CHR="0B"
> DIR="04"
> EXEC="06"
> FILE="00"
> MULTIHARDLINK="06"
> LINK="06"
> MISSING=00 # Not sure what this is
> ORPHAN="09"
> FIFO="06"
> SOCK="0B"
> OTHER=06
> 
> export NNN_FCOLORS="$BLK$CHR$DIR$EXEC$FILE$MULTIHARDLINK$LINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"
> ```

how do you theme nnn

**Comment by duganchen** [comment]
By setting the FCOLORS environment variable. Anyway, I've created an nnn theming page on their wiki:

https://github.com/jarun/nnn/wiki/Themes
