### ISSUE TITLE
how to get nord theme for gimp?

### ISSUE THREAD

**Issue by momofor** [arcticicestudio/nord#145]
I'm new to gimp and when I go to the official  website ports section and click on the gimp color swatches i only get a text file with all of the nord colors and I really don't how to get it into gimp.

**Comment by momofor** [comment]
closed cause of inactivity :(

**Comment by arcticicestudio** [comment]
Do you mean you're not using it actively anymore or are you disappointed to not get real-time/instant assistance?
Please always remember that most OSS projects are driven by humans (with "real" life tasks) that spend their free time to work on these and are not payed to monitor GitHub issues 24/7. Many of them work hard to make projects better every day and expectations from users who think they bought live support can be sometimes frustrating.
There are currently 500+ items for issues, PRs and support requests in my notifications, emails and TODO lists so I can not reply to everything within minutes. My answer is not meant badly, just a request to be more considerate.

Anyway, I guess you're referring to the [“GIMP, Krita and Inkscape“][d] section in color swatches documentation which are actually no port projects but simple [color palettes][w]. The file is **not** a [GIMP UI theme][gt] but [GIMP color palette][gcp] that can be imported to simplify the usage of [Nord color palettes][ncp] without the need to copy & paste the hexadecimal color values over and over again.

[d]: https://www.nordtheme.com/docs/swatches#gimp-krita-and-inkscape
[w]: https://en.wikipedia.org/wiki/Palette_(computing)
[gcp]: https://docs.gimp.org/en/gimp-concepts-palettes.html
[gt]: https://docs.gimp.org/2.6/en/gimp-pimping.html#gimp-prefs-theme
[ncp]: https://www.nordtheme.com/docs/colors-and-palettes
