### ISSUE TITLE
Guake theme

### ISSUE THREAD

**Issue by kepbod** [arcticicestudio/nord#15]
[Guake Terminal](http://guake.org/) is one popular top-down terminal for Gnome. Would you like to add supports for it. Thanks!

**Comment by arcticicestudio** [comment]
[Nord Guake](https://github.com/arcticicestudio/nord-guake) is already available as a official port project 😄

**Comment by kepbod** [comment]
Great! I did not notice it.

**Comment by arcticicestudio** [comment]
No problem, I try to keep the [port projects](https://github.com/arcticicestudio/nord#port-projects) section up-to-date to make it easy for users to find available projects, but there are also plans for a project website with a nice presentation of all available ports.
