### ISSUE TITLE
Tmux color scheme?

### ISSUE THREAD

**Issue by heliostatic** [arcticicestudio/nord#16]
Would it be possible to get a tmux color scheme, similar to this one based on the vim-gotham theme? https://github.com/shaneog/tmux-colors-gotham

**Comment by arcticicestudio** [comment]
Sure, this is also already a planned port project 😉 
You can find more information in the epic issue #18 in the **CLI Applications** section.
I'll notify you as soon as the specific backlog issue is created so you can track the progress or contribute ideas for this port project.

**Comment by arcticicestudio** [comment]
🚢 Shipped with plugin release version 🏷 [0.1.1](https://github.com/arcticicestudio/nord-tmux/releases/tag/v0.1.1).
