### ISSUE TITLE
Port for QTerminal

### ISSUE THREAD

**Issue by lil-skelly** [arcticicestudio/nord#172]
I know at least 23 people that use QTerminal and want a nord theme on it. I would make the theme myself its just that creating a theme for Q sucks since it has some really weird syntax.

**Comment by sfzaw** [comment]
Konsole color scheme works for QTerminal. 

- Download it from [here](https://github.com/arcticicestudio/nord-konsole/releases/tag/v0.1.0)
- paste `nord.colorscheme` file to `~/.config/qterminal.org/color-schemes`
- Pick nord theme from qterminal> File> Preference> Appearence> Color scheme : nord

 Do me a favor and let those "23 people" know they can use any Konsole theme on qterminal.
