### ISSUE TITLE
Migrate Nord repositories from `arcticicestudio` to `nordtheme`

### ISSUE THREAD

**Issue by svengreb** [arcticicestudio/nord#185]
The latest [“Northern Post — The state and roadmap of Nord“][1] announcement described the plans for the migration to [Nord‘s new home home on GitHub][2] and this _epic_ (GitHub [_tasklist_][3]) is used to track to overall process.
For a better visualization, with a time-based structure and general overview see [the “Roadmap ⧚“ view of Nord‘s “Planning & Roadmaps“ project board][4] as well as the [“Active ↻“ view][5] for the current iteration.

The main goal is to migrate the repositories itself to this new `nordtheme` organization, including…

- …adjustments of any hyperlinks to previous `arcticicestudio` references as well as other, already migrated, repositories.
- …adjustments of any copyright information, removing [_Arctic Ice Studio_ as Nord brand due to its retirement][6].
- …adaption to updated documentation and style conventions which reduces the need to solve this through individual issues again afterwards.
- …adaption to [Nord‘s new “Planning & Roadmaps“ project board][7] by adding existing, already triaged or active, issues and preparing “fresh“ issues for the follow-up triaging later on.

[1]: https://github.com/orgs/nordtheme/discussions/183
[2]: https://github.com/orgs/nordtheme/discussions/183#user-content-nords-new-home-on-github
[3]: https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists
[4]: https://github.com/orgs/nordtheme/projects/1/views/11
[5]: https://github.com/orgs/nordtheme/projects/1/views/7
[6]: https://github.com/orgs/nordtheme/discussions/183#user-content-retire-arctic-ice-studio-as-nord-brand
[7]: https://github.com/orgs/nordtheme/projects/1

**Comment by A1Mex-web** [comment]
To update the repository links and reflect the new organization `nordtheme`, it is essential to follow the steps outlined in the migration plan. Here is a detailed guide to ensure that the links are updated correctly:

1. **Identification of Old Links**: Review all links that point to the old repositories in `arcticicestudio`. This includes links in documents, websites, and any other place where the old repositories were referenced.

2. **Updating Links**: Replace each old link with the new link that points to the `nordtheme` organization. For example, if an old link is `https://github.com/arcticicestudio/repo`, the new link should be `https://github.com/nordtheme/repo`.

3. **Verification of Links**: Once the links are updated, verify that all of them work correctly. You can do this by visiting each link to ensure it directs to the correct page in `nordtheme`.

4. **Documentation and Notifications**: Update any internal or external documentation that references the old repositories. Additionally, notify colleagues and users about the changes to avoid confusion.

5. **Change Log**: Keep a record of the updated links for future references and to ensure that no important links are lost.

If you have any questions or need additional assistance during this process, please do not hesitate to contact the Nord team. Thank you for your collaboration in this migration!Para actualizar los enlaces de los repositorios y reflejar la nueva organización `nordtheme`, es fundamental seguir los pasos descritos en el plan de migración. Aquí tienes una guía detallada para asegurarte de que los enlaces se actualicen correctamente:

1. **Identificación de Enlaces Antiguos**: Revisa todos los enlaces que apunten a los repositorios anteriores en `arcticicestudio`. Esto incluye enlaces en documentos, sitios web, y cualquier otro lugar donde se hayan referenciado los repositorios antiguos.

2. **Actualización de Enlaces**: Reemplaza cada enlace antiguo con el nuevo enlace que apunte a la organización `nordtheme`. Por ejemplo, si un enlace antiguo es `https://github.com/arcticicestudio/repo`, el nuevo enlace debería ser `https://github.com/nordtheme/repo`.

3. **Verificación de Enlaces**: Una vez actualizados los enlaces, verifica que todos funcionen correctamente. Puedes hacer esto visitando cada enlace para asegurarte de que dirige a la página correcta en `nordtheme`.

4. **Documentación y Notificaciones**: Actualiza cualquier documentación interna o externa que reference los repositorios antiguos. Además, notifica a los colaboradores y usuarios sobre los cambios para evitar confusiones.

5. **Registro de Cambios**: Mantén un registro de los enlaces actualizados para futuras referencias y para asegurarte de que no se pierdan enlaces importantes.

Si tienes alguna pregunta o necesitas asistencia adicional durante este proceso, no dudes en contactar al equipo de Nord. ¡Gracias por tu colaboración en esta migración!
