### ISSUE TITLE
Cursor disappears in insert mode with Neovim

### ISSUE THREAD

**Issue by maxcountryman** [arcticicestudio/nord#205]
I'm not quite sure what's going on here...when I first setup Neovim, insert mode was working fine (i.e. it showed a skinny version of the cursor marker). After I setup my theme the cursor completely disappeared when in insert mode.

I'm using macOS 10.14.5, TMUX 2.8, NVIM v0.3.8, and this package to install and setup Nord.

Any help is greatly appreciated--this is surprisingly annoying!

**Comment by arcticicestudio** [comment]
> Related to nordtheme/vim#72 

Hi @maxcountryman, I guess this is related to your _tmux_ setup. There are several issues like nordtheme/vim#72 where _tmux_ is not correctly configured for the running environment and terminal emulator.
Could you please follow the instructions in https://github.com/arcticicestudio/nord-tmux/issues/15#issuecomment-341715220 to see if it fixes you problem?

**Comment by arcticicestudio** [comment]
@maxcountryman Any update on the problem? have you been able to resolve it using the instructions from the linked comment?

**Comment by maxcountryman** [comment]
Nope—this continues to be an issue.
