### ISSUE TITLE
My colorcheme is incorrect

### ISSUE THREAD

**Issue by MykolaVaskevych** [arcticicestudio/nord#223]
i rad this issue[https://github.com/arcticicestudio/nord-vim/issues/166](url), tried a code form them but it`s doesn't work.
here it is how my vim looking now 
![image](https://user-images.githubusercontent.com/58508966/106368146-34d77100-6350-11eb-8479-c62fa64cada2.png)

**Comment by arcticicestudio** [comment]
Hi @VaskMykola :wave:

Based on the color from the screenshot my first guess is that you're missing the actual color theme for your terminal.
Please check if there's a Nord port for your terminal available and install it if so, otherwise post the name of your terminal.
