### ISSUE TITLE
plug install failed online

### ISSUE THREAD

**Issue by MagicVin** [arcticicestudio/nord#227]
Is there a way to install nord-vim offline?
I can't install plug online since the network police in China.

Will
Thanks!

**Comment by felix-kyun** [comment]
On the installation page you will find the manual section.
Link:https://www.nordtheme.com/docs/ports/vim/installation

```
Manual
To install Nord Vim manually, download the latest version or clone the repository.
Afterwards copy the nord.vim file into the .vim/colors located in your home directory.
```
