### ISSUE TITLE
Chromium theme?

### ISSUE THREAD

**Issue by zomban** [arcticicestudio/nord#23]
I see that a Firefox theme is in the works, are there plans for a chromium theme? Once the GTK+ theme is up and running, will using the "Use GTK+ theme" button automatically sync the color of chromium to the colors as set in the GTK+ theme?

**Comment by arcticicestudio** [comment]
Chromium will adapt the colors of the GTK+ theme and if you enable the *Use system title bar and borders* option it'll also use the GTK+ window styles.
You can see the result using the awesome [Arc](https://github.com/horst3180/arc-theme) GTK theme on the second screenshot below.

![ghi-23-scrot-chromium-theme-options](https://cloud.githubusercontent.com/assets/7836623/24567487/48a97cf2-165e-11e7-9ca7-babdfc71ccf2.png)

![ghi-23-scrot-chromium-gtk-theme](https://cloud.githubusercontent.com/assets/7836623/24567490/4b096624-165e-11e7-9257-466a205fa94b.png)
