### ISSUE TITLE
Higher-contrast variants?

### ISSUE THREAD

**Issue by escherba** [arcticicestudio/nord#231]
Hi, I really like Nord colors, but wish there was a higher-contrast variant of this theme with a slightly darker background. For example, one of my favorite color schemes, [Lucius](https://github.com/jonathanfilip/lucius), provides several variants (particularly useful if one's monitor is imperfect!). Perhaps this feature already exists but I somehow missed it when reviewing code and docs -- if someone could point it to me, that would be great.

Thanks!

**Comment by frosetrain** [comment]
I too think that a higher-contrast variant or Nord would be nice. When I decrease my screen brightness at night, Nord's low contrast ratio makes it hard to see the text.

**Comment by jasonlong** [comment]
I have a fork with a slightly darker background that gives me contrast I prefer. 

https://github.com/jasonlong/nord-vim
