### ISSUE TITLE
Consider more contrast for comments

### ISSUE THREAD

**Issue by josh-k-cb** [arcticicestudio/nord#241]
## Description

The theme could benefit from more color contrast for comments in Typescript files, especially during diff.

Standard comment:
![image](https://user-images.githubusercontent.com/70601887/103059409-073e2180-4573-11eb-8657-8ca8d11fb471.png)

Diff comment:
![image](https://user-images.githubusercontent.com/70601887/103059387-f55c7e80-4572-11eb-81df-a66cc3b1c738.png)

I've personally applied these:
```
  "editor.tokenColorCustomizations": {
    "[Nord]": {
      "comments": "#81A1C1"
    }
  },
  "workbench.colorCustomizations": {
    "[Nord]": {
      "diffEditor.insertedTextBackground": "#5E81AC33"
    }
  }
```

to get this:

Standard comment:
![image](https://user-images.githubusercontent.com/70601887/103059514-55ebbb80-4573-11eb-85b2-0be7395cbddf.png)

Diff comment:
![image](https://user-images.githubusercontent.com/70601887/103059497-4cfaea00-4573-11eb-951c-be7ec2b13e11.png)

My solution might not be 'pure Nord' but I can read comments during diff, which is nice

### Benefits

Readability

### Possible Drawbacks

Objective opinion

**Comment by crizant** [comment]
This is exactly what i've been looking for, thanks!
Finally I can see comments in the git diff panel. I think this should be applied by default.
