### ISSUE TITLE
Name of the File Icons Used in the SideBar of this Image.

### ISSUE THREAD

**Issue by ajimae** [arcticicestudio/nord#247]
## Description

This is just a simple question. Can we get the name of the file icon installed for this team as can be seen in the official image.

### Benefits

Can help us to easily search for the File Icons using the name as against using Google image searches.

### Possible Drawbacks

None

## Example

![image](https://user-images.githubusercontent.com/32770340/187794848-963b26e7-d225-40fe-86d9-bf158b7fe4ce.png)

## Additional Context

Whoever knows the name of the Icons should help.

## References

See File Icons below 👇🏽 
<img width="228" alt="ui-overview-jsx" src="https://user-images.githubusercontent.com/32770340/187795187-82aa3822-01f1-4719-b586-3d3ed3311e07.png">

## Potential Solution

N/A

**Comment by cody-quinn** [comment]
I saw this image and instantly thought the same thing, if anyone has an answer that'd be great.

Edit: Found it! https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme-icons
