### ISSUE TITLE
Xcode port project

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord#35]
### <img src="https://developer.apple.com/apple-logo.svg" width=32 height=32/> Xcode
> The Xcode IDE is at the center of the Apple development experience. Tightly integrated with the Cocoa and Cocoa Touch frameworks, Xcode is an incredibly productive environment for building apps for Mac, iPhone, iPad, Apple Watch, and Apple TV.

🌐 [Official website](https://developer.apple.com/xcode/)

🏁 Process ▮▮▮▮▮▮▮▮▮▮ `100%`
*ETA*: 2017-04-23 ✔️
➡️ Released on 2017-04-23 with initial version 🏷 [0.1.0](https://github.com/arcticicestudio/nord-xcode/releases/tag/v0.1.0)

❯ **Title**: Nord Xcode
❯ **Project**: [`nord-xcode`](https://github.com/arcticicestudio/nord-xcode)
❯ **Related issues**: [arcticicestudio/nord-xcode #1](https://github.com/arcticicestudio/nord-xcode/issues/1)
  - Request #27 by @ornithocoder

**Comment by ornithocoder** [comment]
It looks awesome! Thank you very much!
