### ISSUE TITLE
Shell prompt?

### ISSUE THREAD

**Issue by ghost** [arcticicestudio/nord#41]
Hey, this might not be best way to ask this, but where can I find your shell prompt? It's amazing and I don't see it anywhere in your repositories.

Keep up great work!

**Comment by arcticicestudio** [comment]
Nice to see you like it 😄 
You can check out my dotfile repository called [igloo](https://github.com/arcticicestudio/igloo). My [`prompt`](https://github.com/arcticicestudio/igloo/blob/develop/snowblocks/bash/core/prompt) plugin is located in the `bash` *snowblock*.
