### ISSUE TITLE
Xcode 9 Asset Catalog

### ISSUE THREAD

**Issue by ornithocoder** [arcticicestudio/nord#45]
Xcode 9 added color support to [asset catalogs](https://devstreaming-cdn.apple.com/videos/wwdc/2017/201fz90p4yq582o/201/201_whats_new_in_cocoa_touch.pdf). It would be nice to have an official Nord asset catalog that could be dragged and dropped in iOS and macOS projects. 

Asset Catalogs colors can be used in

1. Interface Builder, and
2. Programmatically - using `UIColor(named:)`.

Example:

<img width="993" alt="screen shot 2017-06-24 at 7 27 47 pm" src="https://user-images.githubusercontent.com/19753339/27510545-485b7596-5913-11e7-8914-dcb8dc7c724f.png">

Suggestion: [Nord.xcassets.zip](https://github.com/arcticicestudio/nord/files/1099899/Nord.xcassets.zip)

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 
Sorry for my late reply, I've been busy with my job.

I think this issue should be moved to [arcticicestudio/nord-xcode](https://github.com/arcticicestudio/nord-xcode) to be provided as additional asset/resource.

**Comment by arcticicestudio** [comment]
Relocated to arcticicestudio/nord-xcode#2
