### ISSUE TITLE
PyCharm

### ISSUE THREAD

**Issue by pmatias** [arcticicestudio/nord#51]
Any plans on making a port to PyCharm???

**Comment by pemedina** [comment]
Just use the intelliJ IDEA port?
https://github.com/arcticicestudio/nord-intellij-idea-syntax

![screenshot 2017-10-20 a las 08 12 08](https://user-images.githubusercontent.com/2750254/31818493-b578e5fa-b598-11e7-988a-9c6b4ebbbbcc.png)

**Comment by arcticicestudio** [comment]
Like @pemedina mentioned the [Nord IntelliJ Idea Syntax](https://github.com/arcticicestudio/nord-intellij-idea-syntax) port project works for all *JetBrains* IDEs. Please read the answer in #48 for further details :smile:

**Comment by pmatias** [comment]
Yes! I just assumed it wasn't available because there's no mention of Python on the IntelliJ Idea Nord project page.

Just installed it, works like a charm! thanks!
