### ISSUE TITLE
Alacritty color theme?

### ISSUE THREAD

**Issue by sivakov512** [arcticicestudio/nord#58]
[Alacritty](https://github.com/jwilm/alacritty) is a really cool terminal emulator. What about the color theme for him? :)

**Comment by dominiklohmann** [comment]
There's one in the alacritty wiki: https://github.com/jwilm/alacritty/wiki/Color-schemes

**Comment by sivakov512** [comment]
Cool!
Maybe add it to README?

**Comment by arcticicestudio** [comment]
[Nord Alacritty][repo] is already available as official port project. It will be added, including all new port projects to the Nord documentations as soon as the new release version gets prepared.

[repo]: https://github.com/arcticicestudio/nord-alacritty
