### ISSUE TITLE
Support for PhpStorm

### ISSUE THREAD

**Issue by ckipp01** [arcticicestudio/nord#59]
I originally thought it'd be easy to translate what you have for IntelliJ would be easy to port over to PhpStorm, but I couldn't get it working. I'd love to have support for PhpStorm.

**Comment by arcticicestudio** [comment]
Please see #48, it has already been requested and should work fine out-of-the-box using [Nord IntelliJ IDEA Syntax][ref].

[ref]: https://github.com/arcticicestudio/nord-intellij-idea-syntax
