### ISSUE TITLE
Creating own port

### ISSUE THREAD

**Issue by sylveon** [arcticicestudio/nord#62]
What are the guidelines if someone wants to port the theme to a program and distribute it? Are there any limitations I must respect or credits I must give? I plan on adding the color palette to my https://github.com/sylveon/terminology-themes project

**Comment by arcticicestudio** [comment]
Nord is currently [migrating to the MIT license][gh-55] so if you'd like to add the theme to your theme collection project only make sure to include the copyright, license and author notice in the file.

Also if the target application doesn't exists as [official port project][pp] yet you can submit a request issue.

[gh-55]: https://github.com/arcticicestudio/nord/issues/55
[pp]: https://github.com/arcticicestudio/nord#port-projects

**Comment by sylveon** [comment]
Looks good to you? https://github.com/sylveon/terminology-themes/commit/35a053d28ef45c3961457fe84f69e526c6729c9f

**Comment by arcticicestudio** [comment]
Looks good :+1:
