### ISSUE TITLE
Font?

### ISSUE THREAD

**Issue by s0kil** [arcticicestudio/nord#66]
What font is this?
https://camo.githubusercontent.com/37e083316fe76a8b5f00d584b8fd3054ada5427a/68747470733a2f2f63646e2e7261776769742e636f6d2f61726374696369636573747564696f2f6e6f72642f646576656c6f702f7372632f6173736574732f6e6f72642d6c6f676f2d62616e6e65722e737667

**Comment by arcticicestudio** [comment]
*[Helvetica][h] Neue Light*. The Inkscape/Illustrator source of the [Nord Logo][nl] and all other [assets][a] are also available in the repository.

[a]: https://github.com/arcticicestudio/nord/tree/develop/src/assets
[h]: https://en.wikipedia.org/wiki/Helvetica
[nl]: https://github.com/arcticicestudio/nord/blob/develop/src/assets/nord-logo.ai
