### ISSUE TITLE
nord-notepadplusplus repo un available

### ISSUE THREAD

**Issue by raisedadead** [arcticicestudio/nord#8]
https://github.com/arcticicestudio/nord-notepadplusplus is a 404 on the README.md
Consider removing the link?

**Comment by arcticicestudio** [comment]
Hi, thanks for your report.
The Notepad++ port project is planned for later.
I've created the empty repository for now to indicate that there is content to come.

**Comment by arcticicestudio** [comment]
@raisedadead Just want to let you know that I've released version [0.1.0](https://github.com/arcticicestudio/nord-notepadplusplus/releases/tag/v0.1.0) of the now available Nord Notepad++ port project.

**Comment by raisedadead** [comment]
Thanks @arcticicestudio !
