### ISSUE TITLE
[Request] Icon files

### ISSUE THREAD

**Issue by lee-hyunkyu** [arcticicestudio/nord#91]
Would you ever consider releasing the application specific icon images seen in the banners as an `.icns`?

**Comment by arcticicestudio** [comment]
If you refer to the icons used for the [port project][pp] banners, the source files are available in the [repository][a]. You can simply extract them by either using the Illustrator project files directly or from the SVG files with any editor or SVG tool like [Inkscape][i]. The icons itself have mostly been adapted from the [Numix Icon Theme][n].

Doing so simply allows to export them in any (proprietary/native) format like e.g. `.icns` or `.ico`.

[pp]: https://arcticicestudio.github.io/nord/introduction/port-projects.html
[a]: https://github.com/arcticicestudio/nord/tree/develop/assets
[i]: https://inkscape.org/en/
[n]: https://github.com/numixproject/numix-icon-theme

**Comment by lee-hyunkyu** [comment]
Thanks, I'll take a look at trying that.
